version: "2"
run:
  timeout: 10m
  tests: true
linters:
  enable:
    - bodyclose
    - cyclop
    - decorder
    - dupl
    - errname
    - errorlint
    - copyloopvar
    - forbidigo
    - funlen
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - godox
    - gosec
    - misspell
    - musttag
    - nestif
    - nilnil
    - nlreturn
    - noctx
    - nonamedreturns
    - prealloc
    - promlinter
    - reassign
    - revive
    - tagalign
    - testifylint
    - unconvert
    - unparam
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl_v5
  disable:
    - godot
    - gocyclo
  settings:
    funlen:
      lines: 120
      statements: 80
    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .WithStack(
        - .WithTags(
        - .Combine(
        - .Join(
      ignore-package-globs:
        - "encoding/*"
        - "gopkg.in/yaml.v2*"
      ignore-sig-regexps:
        - .*\.Wrap\w+Error\(
    cyclop:
      max-complexity: 15
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
      disable:
        - err
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - funlen
          - gocyclo
          - gosec
          - lll
          - nilnil
          - noctx
        path: _test\.go
      - linters:
          - dupl
          - errcheck
          - funlen
          - gocyclo
          - gosec
          - lll
          - nilnil
          - noctx
        path: testing.go
      - linters:
          - lll
        source: ^func
    paths:
      - .*/bindata.go$
      - third_party$
      - builtin$
      - examples$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: false
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - .*/bindata.go$
      - third_party$
      - builtin$
      - examples$
