run:
  timeout: 10m
  tests: true
  skip-files:
    - ".*/bindata.go$"
linters:
  enable-all: true
  disable:
    - wsl
    - gochecknoglobals
    - lll
    - scopelint
    - gomnd
    - funlen
    - testpackage
    - goerr113
    - wrapcheck
    - thelper
    - paralleltest
    - exhaustivestruct
    - nlreturn
    - exhaustive
    - errorlint
    - stylecheck
    - forbidigo
    - dupl
    - exhaustruct
    - nosnakecase
    - tagliatelle
    - varnamelen
    - ireturn
