run:
  timeout: 10m
  tests: true
  skip-files:
    - ".*/bindata.go$"
linters:
  enable:
    - bodyclose
    - cyclop
    - decorder
    - dupl
    - errname
    - errorlint
    - execinquery
    - exportloopref
    - forbidigo
    - funlen
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - godox
    - gofmt
    - goimports
    - gosec
    - misspell
    - musttag
    - nestif
    - nilnil
    - nlreturn
    - noctx
    - nonamedreturns
    - prealloc
    - promlinter
    - reassign
    - revive
    - tagalign
    - testifylint
    - unconvert
    - unparam
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
  disable:
    - godot
    - gofumpt # as we have gofmt
    - golint # as we enabled revive
    - gocyclo 

linters-settings:
  wsl:
    # If true append is only allowed to be cuddled if appending value is
    # matching variables, fields or types one line above. Default is true.
    strict-append: true
    # Allow calls and assignments to be cuddled as long as the lines have any
    # matching variables, fields or types. Default is true.
    allow-assign-and-call: true
    # Allow multiline assignments to be cuddled. Default is true.
    allow-multiline-assign: true
    # Allow declarations (var) to be cuddled.
    allow-cuddle-declarations: false
    # Allow trailing comments in ending of blocks
    allow-trailing-comment: false
    # Force newlines in end of case at this limit (0 = never).
    force-case-trailing-whitespace: 0

  funlen:
    lines: 120
    statements: 80

  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
      - .WithTags(
      - .Combine(

    ignorePackageGlobs:
      - "encoding/*"
      - "gopkg.in/yaml.v2*"

  cyclop:
    max-complexity: 15

issues:
  new: true
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: false

  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - lll
        - funlen
        - nilnil
    - path: testing.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - lll
        - funlen
        - nilnil

    - linters:
        - lll
      source: "^func"

    # Exclude wannabe compiler
    - path: /
      linters:
        - typecheck
