run:
  timeout: 10m
  tests: true
  skip-files:
    - ".*/bindata.go$"
linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - lll
    - scopelint
    - gomnd
    - funlen
    - testpackage
    - goerr113
    - wrapcheck
    - thelper
    - paralleltest
    - exhaustivestruct
    - nlreturn
    - exhaustive
    - errorlint
    - stylecheck
    - forbidigo
    - dupl
    - exhaustruct
    - nosnakecase
    - tagliatelle
    - varnamelen
    - ireturn

linters-settings:
  wsl:
    # If true append is only allowed to be cuddled if appending value is
    # matching variables, fields or types on line above. Default is true.
    strict-append: true
    # Allow calls and assignments to be cuddled as long as the lines have any
    # matching variables, fields or types. Default is true.
    allow-assign-and-call: true
    # Allow multiline assignments to be cuddled. Default is true.
    allow-multiline-assign: true
    # Allow declarations (var) to be cuddled.
    allow-cuddle-declarations: false
    # Allow trailing comments in ending of blocks
    allow-trailing-comment: false
    # Force newlines in end of case at this limit (0 = never).
    force-case-trailing-whitespace: 0

issues:
  new: true
