name: 'Run golangci-lint'
description: 'Lint go linter for upfluence repo.'
author: 'Karim Assaly (upfluence)'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    required: true
    default: ${{ github.token }}
  module_download_mode:
    description: '-mod=<mode> value'
    required: false
runs:
  using: 'composite'
  steps:
    - name: golanci-lint
      uses: reviewdog/action-golangci-lint@v2
      with:
        github_token: ${{ inputs.github_token }}
        golangci_lint_flags: "-c ${{ github.action_path }}/.golangci.yml"
        cache: false 
        reporter: github-pr-review
        fail_on_error: true

branding:
  icon: 'check-circle'
  color: 'blue'
