name: 'Run golangci-lint'
description: 'Lint go linter for upfluence repo.'
author: 'Karim Assaly (upfluence)'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    required: true
    default: ${{ github.token }}
  go-version:
    description: 'go version'
    required: false
    default: '1.21.x'
runs:
  using: 'composite'
  steps:
    - name: golanci-lint
      uses: reviewdog/action-golangci-lint@v2
      with:
        github_token: ${{ inputs.github_token }}
        golangci_lint_flags: "-c ${{ github.action_path }}/.golangci.yml --new"
        cache: false 
        reporter: github-pr-review
        fail_on_error: true
        go_version: ${{ inputs.go-version }}
        filter_mode: added
    - name: staticcheck
      uses: dominikh/staticcheck-action@v1.3.0
      with:
        min-go-version: ${{ inputs.go-version }}
      env:
        OKTA_CLIENT_SECRET: ${{ secrets.OKTA_CLIENT_SECRET }}
        OKTA_CLIENT_ID: ${{ secrets.OKTA_CLIENT_ID }}

branding:
  icon: 'check-circle'
  color: 'blue'
