name: 'Run golangci-lint'
description: 'Lint go linter for upfluence repo.'
author: 'Karim Assaly (upfluence)'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    required: true
    default: ${{ github.token }}
  module_download_mode:
    description: '-mod=<mode> value'
    required: false
  go-version:
    required: false
    type: string
    default: '1.20.x'
runs:
  using: 'composite'
  steps:
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.go-version }}
        cache: false
    - name: golanci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.53.3
        args: -c ${{ github.action_path }}/.golangci.yml
        only-new-issues: true

branding:
  icon: 'check-circle'
  color: 'blue'
