name: 'Run golangci-lint'
description: 'Lint go linter for upfluence repo.'
author: 'Karim Assaly (upfluence)'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    required: true
    default: ${{ github.token }}
  go-version:
    description: 'go version'
    required: false
    default: '1.25.x'
runs:
  using: 'composite'
  steps:
    - name: golanci-lint
      uses: reviewdog/action-golangci-lint@v2
      with:
        golangci_lint_version: 'v2.5.0'
        github_token: ${{ inputs.github_token }}
        golangci_lint_flags: "-c ${{ github.action_path }}/.golangci.yml --new"
        cache: false 
        reporter: github-pr-review
        fail_level: 'any'
        go_version: ${{ inputs.go-version }}
        filter_mode: added

branding:
  icon: 'check-circle'
  color: 'blue'
