name: 'Run golangci-lint'
description: 'Lint go linter for upfluence repo.'
author: 'Karim Assaly (upfluence)'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    required: true
    default: ${{ github.token }}
  module_download_mode:
    description: '-mod=<mode> value'
    required: false
  go-version:
    required: false
    type: string
    default: '1.20.x'
runs:
  using: 'composite'
  steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go-version }}
    - name: install golanci-lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.53.3
    - name: golangci-lint version
      run: golangci-lint --version
    - name: trigger golangci-lint
      run: golangci-lint run

branding:
  icon: 'check-circle'
  color: 'blue'
